### PR TITLE
New handling for distros with python3 native packages

### PR DESCRIPTION
**Pull request by cameronbrunner**

### CODE REVIEW

**Comment by tprestegard** [comment]
The only thing that isn't clear to me is what is provided by `rh-python36-python-devel` and whether or not we need some equivalent in in 7.7 installs.

**Comment by tpdownes** [comment]
@tprestegard my recollection is that this package comes in via `python3-virtualenv` (or similarly named) so it might not really matter.

Note #611 for proper package names under 8.x. They have setup the RPMs so that several package names work, but I've used the real names in #611 .

**Comment by cameronbrunner** [comment]
I have done the installs on our cent 7.7 and rhel 7.7 installations successfully.  The packages included in the above list are the python ones that get installed during a normal yum install python3.  The primary purpose of these lists is to support offline installation scenarios thus the need for a more comprehensive list.

**Comment by tprestegard** [comment]
Got it! Looks good.

**Pull request merged**
