### PR TITLE
Support installation of Python 3.6 from base RHEL/CentOS repos

### PR DESCRIPTION
**Pull request by tpdownes**
Install Python 3.6 from base repos on RHEL/CentOS 7.7+ and 8.x.

### CODE REVIEW

**Comment by tpdownes** [comment]
The unclear part in #610 (both before and now) is whether you intend to use `virtualenv` or `venv`. In your installer script (for <7.7) and in the Puppet code in this PR, you appear to be installing the `virtualenv` package but going on to use `venv`.

I don't believe you need the package to use `venv`, a "built-in" to Python 3.

**Comment by cameronbrunner** [comment]
So you are suggesting we remove the virtualenv packages from both the installer and the puppet code?  I think that should be fine...  They probably never were removed when we did the python2-python3 change.

**Comment by tpdownes** [comment]
I'm suggesting that you or @tprestegard analyze the code ecosystem (incl. Unisight nodes) and arrive at an appropriate conclusion with respect to the `virtualenv` package installations in #610 and #611. I will remove them from this PR on that advice.

**Comment by cameronbrunner** [comment]
I am giving it a shot with #612.  Based on your  analysis I don't think we need it but I need  to run some tests to be  sure.  The only use is for creating the /opt/tortuga directory.

**Pull request merged**
