### PR TITLE
Add check for existing node in addHosts

### PR DESCRIPTION
**Pull request by dtougas**
If a node tries to register itself, and there is already a record in the DB with the same name, this results in a duplicate key error being thrown by the DB. The net result is that this condition can leave node requests in the pending/ADD state for ever as they are not properly cleaned-up.

This MR adds a check early-on in the addNode process to see if an existing node already exists with the same name. If it does, an exception is thrown immediately, allowing callers to deal with the repercussions before too much other processing has been done.

### CODE REVIEW

**Comment by dtougas** [comment]
I accidentally pushed this patch to the `7.1` branch, but my testing is showing that it works. There is still a slight possibility for a race condition if a single node tries to add itself multiple times in succession (with little time between each request), but I don't think that should happen very often, if at all. (cc @tpdownes)

**Comment by tpdownes** [comment]
When you say "pushed" you literally mean `git push` to the `7.1` branch?

**Comment by dtougas** [comment]
Yeah, I meant to push it to a branch, but accidentally pushed straight to the 7.1 branch.

**Comment by dtougas** [comment]
This is the commit: https://github.com/UnivaCorporation/tortuga/commit/37e39c9051b00a591af759249e41a9b5df284d6e

**Comment by tpdownes** [comment]
Sounds fine to me. Are you planning on more testing or should I consider it complete?

**Comment by dtougas** [comment]
No more testing planned at this point. I was able to duplicate the issue prior to this fix, and the issue went away after this fix. So for now, I consider this done.

**Review by cameronbrunner — APPROVED** [review]
LGTM!

**Pull request merged**
