### PR TITLE
Use last release of pip (20.2) before important resolver change

### PR DESCRIPTION
**Pull request by tpdownes**
These changes ensure that

* The installer node is upgraded to the latest 20.2.x of pip
    * via the install shell script
* The installer node is upgraded to a 50.3.x release of setuptools
    * via the install shell script
* All qmaster/execd nodes are upgraded to the latest 20.2.x
    * via the tortuga core puppet module

We want to pin on this version because of [anticipated package resolver changes in 20.3][resolver]

[resolver]: https://discuss.python.org/t/announcement-pip-20-2-release/4863

### CODE REVIEW

**Comment by cameronbrunner** [comment]
@tpdownes is there something specific about 20.2 that you are interested in or is it simply the last one prior to the big change?

**Comment by tpdownes** [comment]
Historically, we've hit a lot of roadblocks during installation because we don't track the contemporary releases (e.g. the python3 changes in CentOS 7.6/8.x). That said, we know problems are coming in 20.3 that we should avoid until we can handle them. So aligning all the code on 20.2 until we're ready to move past 20.3 seems like the thing to do.

A while back, I lost a few days to running on pip 9.x (the upgrade was improperly ordered) a few months back which is why the upgrade to 20.1 in the Puppet code was there in the first place. The best way to avoid lost days in the future is to stay current in the first place, subject to problems we can clearly infer from the release notes (like resolver change).

**Comment by cameronbrunner** [comment]
@dtougas your thoughts on this?

**Comment by dtougas** [comment]
I am OK with it, though I have not tested this in any environment yet.

**Comment by dtougas** [comment]
@tpdownes Would you mind changing this PR to merge into the branch called `scale-set-scale-down` instead? This branch is being developed in parallel with the 2.2 release and will shortly after become the 2.2.1 release.

**Review by cameronbrunner — APPROVED** [review]
LGTM!

**Comment by cameronbrunner** [comment]
@dtougas I changed the target branch.  Please merge when you are comfortable.

**Pull request merged**
