### PR TITLE
Ensure Apache cache is reset when certificate authorities are updated

### PR DESCRIPTION
**Pull request by tpdownes**
This is the more "Puppet" way of doing what you're doing with the `test -d`

### CODE REVIEW

**Comment by tpdownes** [comment]
I haven't yet tested and won't until Monday.

**Comment by tpdownes** [comment]
It might make strict sense for the `exec` to run as the `apache` user.

**Comment by cameronbrunner** [comment]
Let me know if this works.

**Comment by tpdownes** [comment]
I tested by taking a running system and running

```
rm -rf /var/cache/mod_proxy/
rm -f /var/www/tortuga/ca.pem
puppet agent -t
```

I found it necessary to add a few lines to ensure that a file resource in `tortuga_kit_base::core` which downloads the CA file to all systems comes only after the CA file is created and the HTTPD daemon is up. This particular change is only needed on the installer, but I also tested it on a qmaster node and it behaved as you'd expect / as it did prevoiusly.

Good to go.

**Pull request merged**
